steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:latest', 
      '-f', 'docker/Dockerfile', 
      '.'
    ]
images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:latest'

substitutions:
  _REGION: asia-south1
  _REPO_NAME: cloud-run-jobs-repo
  _IMAGE_NAME: gsheets-scheduler